sudo: required
services:
  - docker
before_install:
  - docker build -t nareshpathuru/jft:1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push nareshpathuru/jft:1.0
notifications:
  email:
    recipients:
      - info1@cloudnloud.com
    on_success: always
    on_failure: always
